### ISSUE TITLE
[BE] GET oauth/callback/?code=${code}

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Server#19]
## 이슈 사항
Plugin은 클라이언트 측에서 OAuth인증을 진행할 수 없기 때문에
중계서버를 두고 해당 서버에서 인증을 진행해야 합니다.

## API Endpoint
**GET** `oauth/callback/?code=${code}`

<br />

## Todo 리스트
- [ ] OAuth인증 callback URL에 대응하여 oauth인증을 해야 합니다.
- [ ] query로 받게 될 code값을 가지고 accessToken을 응답으로 받아야 합니다.
- [ ] accessToken을 서버측에 캐싱 해놓아야 합니다.
- [ ] 성공적으로 accessToken을 발급 받았다면, connect html을 응답으로 보내주어야 합니다.

<br />

## 응답 (Response)
응답 상태 코드
Status Code | Description
-- | --
200 | OK
500 | Internal Server Error

<br/>

### 성공 결과
![image](https://github.com/Figci/Figci-Server/assets/48385389/9d9ee770-a339-4478-82b1-cdaa49226347)

<br/>

### 오류 시
```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error",
  } 	
}
