### ISSUE TITLE
[BE] GET /user

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Server#22]
## 이슈 사항
클라이언트에서 요청시 해당 유저의 정보(프로필 이미지, 유저 이름)를 응답으로 보내주어야 합니다.

<br />

## Todo 리스트
- [x] 클라이언트에서 요청이 들어올 시 보내준 `accessToken`을 이용하여 Figma API를 호출하고,
성공적으로 유저 정보를 받아 왔을 시 status `200`으로 클라이언트에게 유저 정보를 전달해주어야 합니다.
- [x] 유효하지 않은 토큰일 경우 **_"Invalid Token"_** 이라는 응답을 보내주어야 합니다.
- [x] 서버측에서 에러가 발생할 시 **_"Internal Server Error"_** 이라는 응답을 보내주어야 합니다.

### End Point
`GET /user`

<br />

## 응답 (Response)
응답 상태 코드
Status Code | Description
-- | --
200 | OK
500 | Internal Server Error
403 | Invalid Token

<br/>

### 성공 응답
```js
{
  result: "succes",
  status: 200,
  content: ${userInformation},
}
```
<br/>

### 오류 응답
```js
// server Error
{
  result: "error",
  status: 500,
  content: "Internal Server Error"
}

// Invalid Token
{
  result: "error",
  status: 403,
  content: "Invalid Token"
}
```
