### ISSUE TITLE
[BE] GET projects/:project-id/pages/?before-version={before-version-id}&after-version={after-version-id}

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Server#6]
## 이슈 사항
유저가 선택한 버전의 각각의 서브트리를 저장 후 공통의 페이지 리스트를 응답으로 보내야 합니다.

<br />

![Image](https://github.com/Figci/Figci-Server/assets/48385389/c5703405-dcdb-4d9e-acff-eb1bd72661e6)

<br/>

## Todo 리스트
- [x]  DB에 해당 결과값이 없다면, Figma API를 Before와 After버전의 서브 트리를 가져와야 합니다.
- [x]  Before와 After버전의 서브 트리 평탄화 하여 DB에 저장합니다.
- [x]  평탄화를 할 떄는 `트리 탐색 알고리즘`을 이용하여 Project스키마, Page스키마에 값을 알맞게 추가한 뒤, 프레임 이하 단위 노드들을 Node 스키마에 저장해야 합니다.
- [x]  두 버전이 공통으로 갖는 페이지 ID값과, 페이지 이름을 response로 응답을 보냅니다.

<br />

### 클라이언트 오류 시
```json
{
  "result": "error",
  "error": {
    "message": "Bad Request",
  } 	
}
```
<br/>

### 서버 오류 시
```json
{
  "result": "error",
  "error": {
    "message": "Internal Server Error",
  } 	
}
```
