### ISSUE TITLE
[BE] 백엔드 초기 구조 작성

### ISSUE THREAD

**Issue by tjd985** [Figci/Figci-Server#8]
## 이슈 사항
공통된 BE작업을 위한 초기 세팅을 하는 테스크 입니다.
`mongoDB Atlas`를 연결 한 뒤
각 API에 대한 라우터를 정의해야 합니다.
각각의 DB스키마를 작성합니다.

<br/>

## DB 스키마
![image](https://github.com/Figci/Figci-Server/assets/48385389/b8957bf1-d9db-44b0-abc4-99bd5e83cefa)

<br />

## API 리스트
GET `projects/:project-id/versions`
GET `projects/:project-id/pages/?before-version={before-version-id}&after-version={after-version-id}`
GET `projects/:project-id/pages/:page-id/diff?before-version={before-version-id}&after-version={after-version-id}`

<br/>

## Todo 리스트
- [x]  **MongoDB 모델 정의**
    - Mongoose를 사용하여 데이터 모델 정의 (예 Document, Page, Node... 등)
    - 각 스키마의 필드값들은 
- [x]  **API 라우팅 및 컨트롤러 구현**
    - CRUD (생성, 읽기, 업데이트, 삭제) 기능을 위한 API 라우트 구현
    - 각 라우트에 대한 컨트롤러 함수 구현
- [x]  **데이터베이스 연결 및 테스트**
    - Mongoose를 사용하여 MongoDB 데이터베이스에 연결
    - 데이터베이스 연결이 정상적으로 작동하는지 테스트
- [x]  **에러 핸들링 및 보안 설정**
    - 에러 핸들링 미들웨어 구현

<br />
